# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-Z_R2fnjC_eNYBBm60ccL1dHrohOCLT
"""

print("Привет! Предлагаю проверить свои знания английского! Расскажи, как тебя зовут!")
# Подсчет счета
score = 0
# Подсчет правильных ответов
flag = 0

name = input("Введите имя ")
print(f"Привет, {name}, начинаем тренировку!")

answer = input("My name ___ Vova ")
print("Ваш ответ: " , answer)
true_answer = "is"

if answer == true_answer:
  print("Ответ верный! \n Вы получаете 10 баллов!")
  #ответ верный: счет +10
  score += 10
  flag += 1
else:
  print(f"Неправильно. \n Правильный ответ: {true_answer}")

answer = input("I ___ a coder ")
print("Ваш ответ: " , answer)
true_answer = "am"
if answer == true_answer:
  print("Ответ верный! \n Вы получаете 10 баллов!")
  score += 10
  flag += 1
else:
  print(f"Неправильно. \n Правильный ответ: {true_answer}")

answer = input("I live ___ Moscow ")
print("Ваш ответ: " , answer)
true_answer = "in"
if answer == true_answer:
  print("Ответ верный! \n Вы получаете 10 баллов!")
  score += 10
  flag += 1
else:
  print(f"Неправильно. \n Правильный ответ: {true_answer}")

print(f"Ваш счет {score}")
print(f"Вот и все, {name}! \n Вы ответили на {flag} вопросов из 3 верно.")

# Подсчет процента
percent = round((flag/3)*100 , 2)

print(f"Вы заработали {score} баллов. Это {percent} процентов.")